# pixkit -- muti lidar
base_link:
  sensor_kit_base_link:
    x: 0.00
    y: 0.00
    z: 1.4
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  velodyne_rear_base_link:
    x: 0.0
    y: -0.56362
    z: -0.30555
    roll: -0.01
    pitch: 0.71
    yaw: -1.580
  # sensor_kit_base_link:
  #   x: 0
  #   y: 0.0
  #   z: 2.0
  #   roll: -0.001
  #   pitch: 0.015
  #   yaw: -0.0364
    
base_link2os_lidar_top:
  x: 0.00
  y: 0.00
  z: 1.4
  roll: 0.0
  pitch: 0.0
  yaw: 3.1075
os_lidar_top2os_lidar_rl:
  x: 0.324
  y: -0.397
  z: -0.359
  roll: 0.518
  pitch: 0.005
  yaw: 0.004
os_lidar_top2os_lidar_rr:
  x: 0.289
  y: 0.379
  z: -0.321
  roll: -0.525
  pitch: -0.002
  yaw: 0.013
base_link2gnss:
  x: -0.9
  y: 0.0
  z: 0.3
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
base_link2rsbp:
  x: 0.786
  y: -0.006
  z: 0.582  
  roll: 0.518
  pitch: 1.351
  yaw: 0.549
base_link2rs16:
  x: 0.00
  y: 0.00
  z: 0.9
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
base_link2zed:
  x: 0.787
  y: -0.031
  z: 1.065
  roll: 0.008
  pitch: 0.292
  yaw: 0.020
base_link2ultrasonic_0:
  x: 1.25
  y: 0.13
  z: 0.35
  roll: 0.0
  pitch: 0.0
  yaw: 0.785
base_link2ultrasonic_1:
  x: 1.25
  y: -0.13
  z: 0.35
  roll: 0.0
  pitch: 0.0
  yaw: -0.785
base_link2ultrasonic_2:
  x: 0.28
  y: 0.5
  z: 0.0
  roll: 0.0
  pitch: 0.0
  yaw: 1.53
base_link2ultrasonic_3:
  x: 0.28
  y: -0.5
  z: 0.0
  roll: 0.0
  pitch: 0.0
  yaw: -1.53
base_link2ultrasonic_4:
  x: -0.28
  y: 0.5
  z: 0.0
  roll: 0.0
  pitch: 0.0
  yaw: 1.53
base_link2ultrasonic_5:
  x: -0.24
  y: -0.5
  z: 0.0
  roll: 0.0
  pitch: 0.0
  yaw: -1.53
base_link2ultrasonic_6:
  x: -1.25
  y: 0.13
  z: 0.4
  roll: 0.0
  pitch: 0.0
  yaw: 2.35
base_link2ultrasonic_7:
  x: -1.25
  y: -0.13
  z: 0.4
  roll: 0.0
  pitch: 0.0
  yaw: -2.35

base_link2ultrasonic_8:
  x: -0.28
  y: 0.55
  z: 0.0
  roll: 0.0
  pitch: 0.0
  yaw: 1.5708
base_link2ultrasonic_9:
  x: -0.28
  y: -0.55
  z: 0.0
  roll: 0.0
  pitch: 0.0
  yaw: -1.5708
base_link2ultrasonic_10:
  x: -1.3
  y: 0.12
  z: 0.2
  roll: 0.0
  pitch: 0.0
  yaw: 3.1416
base_link2ultrasonic_11:
  x: -1.3
  y: -0.12
  z: 0.2
  roll: 0.0
  pitch: 0.0
  yaw: 3.1416

os_lidar_top2camera:
  x: 0.189871
  y: -0.08247789
  z: -0.2053706
  roll: -1.50877693
  pitch: -0.02
  yaw: 1.55820481
