sensing/lidar/top/ouster/os_sensor:
  ros__parameters:
    sensor_hostname: '192.168.1.125'
    udp_dest: ''
    mtp_dest: ''
    mtp_main: false
    lidar_mode: ''
    timestamp_mode: 'TIME_FROM_ROS_TIME'
    udp_profile_lidar: ''
    metadata: ''
    lidar_port: 38672
    imu_port: 48215
sensing/lidar/top/ouster/os_cloud:
  ros__parameters:
    sensor_frame: 'os_sensor_top'
    lidar_frame: 'os_lidar_top'
    imu_frame: 'os_imu_top'
    timestamp_mode: 'TIME_FROM_ROS_TIME'
