/**:
    ros__parameters:
      video_device: "/dev/video2"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "yuyv"
      color_format: "uyvy422"
      image_width: 1920 
      image_height: 1080
      camera_name: "trafficlight"
      camera_info_url: "package://pixkit_sensor_kit_launch/data/camera_info.yaml"
